[manager]
sort_by        = 'btime'
sort_sensitive = false
sort_reverse   = true
sort_dir_first = false
linemode       = 'size'
show_hidden    = true
show_symlink   = true

[preview]
max_width       = 1600
max_height      = 2048

[flavor]
use = "tokyo-night"
# For Yazi 0.4 and above
dark = "tokyo-night"
